apiVersion: v1
kind: Service
metadata:
  name: labor2
  namespace: student-proj
spec:
  externalTrafficPolicy: Cluster
  externalIPs:
    - 10.109.33.178
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8090
  selector:
    name: labor
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}

